<script setup lang="ts">
const {config,content:contact,socials}=useContact(); const {content:site}=useSiteContent(); const {locale,availableLocales,defaultLocale,localePath}=useLocale(); const runtimeConfig=useRuntimeConfig(); const siteUrl=runtimeConfig.public.siteUrl.replace(/\/$/,''); const canonical=computed(()=>`${siteUrl}${localePath('/contact')}`)
const announcement=ref(''); let clearTimer:ReturnType<typeof setTimeout>|undefined
const copyEmail=async()=>{ try{ if(navigator.clipboard?.writeText) await navigator.clipboard.writeText(config.email); else {const area=document.createElement('textarea');area.value=config.email;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();if(!document.execCommand('copy'))throw new Error('copy failed');area.remove()} announcement.value=contact.value.copied }catch{announcement.value=contact.value.copyFailed} clearTimeout(clearTimer);clearTimer=setTimeout(()=>announcement.value='',3000)}
onBeforeUnmount(()=>clearTimeout(clearTimer))
useHead(()=>({htmlAttrs:{lang:locale.value},link:[{rel:'canonical',href:canonical.value},...availableLocales.map(code=>({rel:'alternate',hreflang:code,href:`${siteUrl}${localePath('/contact',code)}`})),{rel:'alternate',hreflang:'x-default',href:`${siteUrl}${localePath('/contact',defaultLocale)}`}]})); useSeoMeta({title:()=>`${contact.value.pageTitle} — ${site.value.artistNameLatin}`,description:()=>contact.value.introduction,ogTitle:()=>`${contact.value.pageTitle} — ${site.value.artistNameLatin}`,ogDescription:()=>contact.value.introduction,ogUrl:()=>canonical.value,ogType:'website'})
</script>
<template><section class="contact-page section-shell"><header><p>{{ site.artistNameLatin }}</p><h1>{{ contact.pageTitle }}</h1><div class="intro">{{ contact.introduction }}</div></header><div class="contact-lines">
  <section v-if="config.showEmail&&config.email"><h2>{{ contact.emailLabel }}</h2><div><a :href="`mailto:${config.email}`">{{ config.email }}</a><button type="button" @click="copyEmail">{{ contact.copyEmail }}</button><p class="notice">{{ contact.inquiryNotice }}</p></div></section>
  <section v-if="config.showPhone&&config.phone"><h2>{{ contact.phoneLabel }}</h2><a :href="`tel:${config.phone.replace(/\s/g,'')}`">{{ config.phone }}</a></section>
  <section v-if="socials.length"><h2>{{ contact.socialLabel }}</h2><nav><a v-for="social in socials" :key="social.label" :href="social.url">{{ social.label }} ↗</a></nav></section>
  <section v-if="config.addressMapUrl"><h2>Location</h2><a :href="config.addressMapUrl">{{ contact.mapLabel }} ↗</a></section>
  <p class="sr-status" role="status" aria-live="polite">{{ announcement }}</p>
</div></section></template>
<style scoped lang="scss">
.contact-page{min-height:calc(100vh - 8rem);padding-block:clamp(6rem,10vw,9rem)}header{display:grid;grid-template-columns:1fr minmax(16rem,.65fr);align-items:end;gap:2rem;margin-bottom:clamp(4rem,7vw,7rem)}header>p{grid-column:1/-1;margin:0;color:var(--accent-strong);font-size:.68rem;letter-spacing:.16em;text-transform:uppercase}h1{margin:0;font-family:var(--font-serif);font-size:clamp(3.25rem,7.5vw,7.5rem);font-weight:400;line-height:.92}.intro{font-family:var(--font-serif);font-size:clamp(1rem,1.5vw,1.3rem);line-height:1.8}.contact-lines{max-width:68rem;margin-left:auto}.contact-lines>section{display:grid;grid-template-columns:minmax(8rem,.4fr) minmax(0,1fr);gap:2rem;padding-block:2.1rem;border-top:1px solid var(--color-line)}h2{margin:0;color:var(--color-muted);font-size:.66rem;font-weight:400;letter-spacing:.1em;text-transform:uppercase}.contact-lines a{font-family:var(--font-serif);font-size:clamp(1rem,2vw,1.65rem)}button{display:block;min-height:44px;margin-top:1rem;padding:0;border:0;border-bottom:1px solid var(--color-line);background:transparent;cursor:pointer;font-size:.7rem}.notice{color:var(--color-muted);font-size:.7rem}nav{display:flex;flex-direction:column;align-items:flex-start;gap:.8rem}.sr-status{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:767px){.contact-page{padding-top:calc(var(--mobile-header-height) + 3rem)}header,.contact-lines>section{grid-template-columns:1fr}header>p{grid-column:auto}}
</style>
