<script setup lang="ts">
const props=defineProps<{slug:string}>(); const {content:news,getBySlug,getAdjacent,categoryName,formatPeriod}=useNews(); const {artworks}=useArtworks(); const {content:site}=useSiteContent(); const {locale,availableLocales,defaultLocale,localePath}=useLocale(); const runtimeConfig=useRuntimeConfig(); const siteUrl=runtimeConfig.public.siteUrl.replace(/\/$/,'')
const item=computed(()=>getBySlug(props.slug)); if(!item.value) throw createError({statusCode:404,statusMessage:'News not found'})
const adjacent=computed(()=>getAdjacent(props.slug)); const related=computed(()=>artworks.value.filter(artwork=>item.value?.relatedArtworkIds.includes(artwork.id))); const canonical=computed(()=>`${siteUrl}${localePath(`/news/${props.slug}`)}`)
const structuredData=computed(()=>{ if(!item.value)return null; const common={ '@context':'https://schema.org',name:item.value.title,description:item.value.summary,image:`${siteUrl}${item.value.image}`,url:canonical.value }
  if(item.value.categoryId==='exhibition'&&(item.value.venue||item.value.location)) return {...common,'@type':'Event',startDate:item.value.publishedAt,endDate:item.value.endAt||undefined,location:{'@type':'Place',name:item.value.venue||undefined,address:item.value.location||undefined}}
  return {...common,'@type':'Article',datePublished:item.value.publishedAt,author:{'@type':'Person',name:site.value.artistNameLatin}}
})
useHead(()=>({htmlAttrs:{lang:locale.value},link:[{rel:'canonical',href:canonical.value},...availableLocales.map(code=>({rel:'alternate',hreflang:code,href:`${siteUrl}${localePath(`/news/${props.slug}`,code)}`})),{rel:'alternate',hreflang:'x-default',href:`${siteUrl}${localePath(`/news/${props.slug}`,defaultLocale)}`}],script:structuredData.value?[{type:'application/ld+json',innerHTML:JSON.stringify(structuredData.value)}]:[]}))
useSeoMeta({title:()=>`${item.value?.title} — ${site.value.artistNameLatin}`,description:()=>item.value?.summary||'',ogTitle:()=>item.value?.title||'',ogDescription:()=>item.value?.summary||'',ogImage:()=>item.value?`${siteUrl}${item.value.image}`:'',ogUrl:()=>canonical.value,ogType:'article',twitterCard:'summary_large_image'})
</script>
<template><article v-if="item" class="news-detail section-shell"><NuxtLink class="back" :to="localePath('/news')">← {{ news.backToNews }}</NuxtLink>
  <header><p class="meta"><span>{{ categoryName(item.categoryId) }}</span><time :datetime="item.publishedAt">{{ formatPeriod(item.publishedAt,item.endAt) }}</time></p><h1>{{ item.title }}</h1><p class="summary">{{ item.summary }}</p><p v-if="item.venue||item.location" class="place"><span v-if="item.venue">{{ item.venue }}</span><span v-if="item.location">{{ item.location }}</span></p></header>
  <NewsImage :src="item.image" :alt="item.alt" :width="item.imageWidth" :height="item.imageHeight" eager :fallback-label="site.common.imagePending" />
  <NewsContentRenderer :blocks="item.content" />
  <section v-if="item.externalVideo" class="detail-video"><VideoEmbed :video="item.externalVideo" :title="item.title" /></section>
  <p v-if="item.externalUrl" class="external"><a :href="item.externalUrl">{{ news.externalLink }} ↗</a></p>
  <section v-if="related.length" class="related"><h2>Related Works</h2><ArtworkGrid :artworks="related" :fallback-label="site.common.imagePending" :desktop-columns="Math.min(3,related.length)" /></section>
  <nav class="adjacent" aria-label="Adjacent news"><NuxtLink v-if="adjacent.previous" :to="localePath(`/news/${adjacent.previous.slug}`)">← {{ news.previous }}<strong>{{ adjacent.previous.title }}</strong></NuxtLink><span v-else/><NuxtLink v-if="adjacent.next" class="next" :to="localePath(`/news/${adjacent.next.slug}`)">{{ news.next }} →<strong>{{ adjacent.next.title }}</strong></NuxtLink></nav>
</article></template>
<style scoped lang="scss">
.news-detail{padding-block:clamp(6rem,10vw,10rem)}.back{display:inline-flex;align-items:center;min-height:44px;margin-bottom:3rem;color:var(--color-muted);font-size:.7rem;letter-spacing:.06em}.news-detail>header{max-width:70rem;margin:0 auto clamp(3rem,6vw,6rem);text-align:center}.meta{display:flex;justify-content:center;gap:1rem;color:var(--color-muted);font-size:.68rem;letter-spacing:.08em;text-transform:uppercase}.meta span{color:var(--accent-strong)}h1{margin:2rem 0;font-family:var(--font-serif);font-size:clamp(3rem,8vw,8rem);font-weight:400;line-height:1.08}.summary{max-width:42rem;margin:0 auto;font-size:clamp(1rem,1.8vw,1.35rem);line-height:1.9}.place{color:var(--color-muted);font-size:.75rem}.place span+span:before{content:' · '}.news-detail>:deep(.responsive-image){margin-bottom:var(--section-gap)}.detail-video,.external,.related{max-width:68rem;margin:var(--section-gap) auto}.external a{display:inline-flex;align-items:center;min-height:48px;border-bottom:1px solid var(--color-text)}.related h2{font-family:var(--font-serif);font-size:clamp(2rem,4vw,4rem);font-weight:400}.adjacent{display:grid;grid-template-columns:1fr 1fr;gap:2rem;margin-top:var(--section-gap);padding-block:2rem;border-block:1px solid var(--color-line)}.adjacent a{display:flex;flex-direction:column;gap:.5rem;font-size:.7rem}.adjacent strong{font-family:var(--font-serif);font-size:1.2rem;font-weight:400}.adjacent .next{text-align:right;align-items:flex-end}@media(max-width:767px){.news-detail{padding-top:calc(var(--mobile-header-height) + 2rem)}}
</style>
